using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using static ImpostersOrdeal.GameDataTypes;
using SmartPoint.AssetAssistant;

namespace ImpostersOrdeal
{
    /// <summary>
    ///  Stores data for easy access.
    /// </summary>
    public static class GlobalData
    {
        public class GameDataSet
        {
            public List<EvScript> evScripts;
            public List<MapWarpAsset> mapWarpAssets;
            public List<PickupItem> pickupItems;
            public ShopTables shopTables;
            public List<Trainer> trainers;
            public EncounterTableFile[] encounterTableFiles;
            public MessageFileSet[] messageFileSets;
            public List<GrowthRate> growthRates;
            public List<UgArea> ugAreas;
            public List<UgEncounterFile> ugEncounterFiles;
            public List<UgEncounterLevelSet> ugEncounterLevelSets;
            public List<UgSpecialEncounter> ugSpecialEncounters;
            public List<Ability> abilities; //Readonly
            public List<Typing> typings; //Readonly
            public List<DamageCategory> damageCategories; //Readonly
            public List<Nature> natures; //Readonly
            public List<TrainerType> trainerTypes; //Readonly
            public List<Pokemon> personalEntries; //Ordered, idx=personalID
            public List<DexEntry> dexEntries; //Ordered, idx=dexID
            public List<Item> items; //Ordered, idx=itemID
            public List<TM> tms; //Ordered, idx=tmID
            public List<Move> moves; //Ordered, idx=moveID
            public Wwise.WwiseData audioData;
            public GlobalMetadata globalMetadata;
            public List<BattleMasterdatas.MotionTimingData> motionTimingData;
            public List<Masterdatas.PokemonInfoCatalog> pokemonInfos;
            public List<PersonalMasterdatas.AddPersonalTable> addPersonalTables;
            public List<UIMasterdatas.PokemonIcon> uiPokemonIcon;
            public List<UIMasterdatas.AshiatoIcon> uiAshiatoIcon;
            public List<UIMasterdatas.PokemonVoice> uiPokemonVoice;
            public List<UIMasterdatas.ZukanDisplay> uiZukanDisplay;
            public List<UIMasterdatas.ZukanCompareHeight> uiZukanCompareHeights;
            public List<UIMasterdatas.SearchPokeIconSex> uiSearchPokeIconSex;
            public AssetBundleDownloadManifest dprBin;

            public Dictionary<string, string> trainerNames;
            public StringBuilder audioSourceLog;

            private readonly bool[] fieldStates = new bool[Enum.GetNames(typeof(DataField)).Length];

            public enum DataField
            {
                EvScripts,
                MapWarpAssets,
                PickupItems,
                ShopTables,
                Trainers,
                EncounterTableFiles,
                MessageFileSets,
                GrowthRates,
                UgAreas,
                UgEncounterFiles,
                UgEncounterLevelSets,
                UgSpecialEncounters,
                Abilities,
                Typings,
                DamageCategories,
                Natures,
                PersonalEntries,
                DexEntries,
                Items,
                TMs,
                Moves,
                AudioData,
                GlobalMetadata,
                UIMasterdatas,
                AddPersonalTable,
                MotionTimingData,
                PokemonInfo,
                DprBin
            }

            public bool IsModified(DataField d)
            {
                return fieldStates[(int)d];
            }

            public void SetModified(DataField d)
            {
                fieldStates[(int)d] = true;
            }

            public Pokemon GetPokemon(int dexID, int formID)
            {
                return dexEntries[dexID].forms[formID];
            }

            public string GetTPDisplayName(TrainerPokemon tp)
            {
                return "Lv. " + tp.level + " " + GetPokemon(tp.dexID, tp.formID).GetName();
            }

            public bool FormDescriptionsExist()
            {
                return Math.Abs(messageFileSets.SelectMany(mfs => mfs.messageFiles)
                    .First(mf => mf.mName.Contains("dp_pokedex_diamond"))
                    .labelDatas.Count - personalEntries.Count) < 2;
            }
        }

        public static FileManager fileManager;
        public static Dictionary<PathEnum, string> randomizerPaths = new();
        public static GameDataSet gameData;
        public static DataTable absoluteBoundaries = new();

        public static DataRow GetBoundaries(AbsoluteBoundary a)
        {
            if ((int)a == -1)
                return null;
            return absoluteBoundaries.Rows[(int)a];
        }

        public static bool IsWithin(AbsoluteBoundary a, int x)
        {
            if ((int)a == -1)
                return true;
            DataRow b = GetBoundaries(a);
            return x >= (int)b[1] && x <= (int)b[2];
        }

        public static int Conform(AbsoluteBoundary a, int x)
        {
            if ((int)a == -1)
                return x;
            DataRow b = GetBoundaries(a);
            x = (int)(Math.Round((double)x / (int)b[3]) * (int)b[3]);
            return Math.Clamp(x, (int)b[1], (int)b[2]);
        }

        public static string GetZoneName(int index)
        {
            if (index == -1)
                return zoneNames.Last();
            return zoneNames[index];
        }

        public static readonly string[] zoneNames = new string[]
        {
            "Jubilife City",
            "Jubilife Poké Mart",
            "Jubilife Pokémon Center 1F",
            "Jubilife Pokémon Center 2F",
            "Jubilife Pokémon Center B1F",
            "Jubilife Pokétch Company 1F",
            "Jubilife Pokétch Company 2F",
            "Jubilife Pokétch Company 3F",
            "Jubilife TV 1F",
            "Jubilife TV 2F",
            "Jubilife TV 3F",
            "Jubilife TV 4F",
            "Jubilife TV Clip Room (Ball Decos)",
            "Jubilife Global Ranking Room",
            "Jubilife Group Ranking Room",
            "Jubilife TV Elevator",
            "Jubilife Building 1 1F (South building)",
            "Jubilife Building 1 2F (South building)",
            "Jubilife Building 2 1F (Condominiums)",
            "Jubilife Building 2 2F (Condominiums)",
            "Jubilife GWS",
            "Jubilife Trainer's School 1F",
            "Jubilife Building 3 1F (Southwest by GWS)",
            "Jubilife Building 3 2F (Southwest by GWS)",
            "Canalave City",
            "Canalave Poké Mart",
            "Canalave Gym (Steel)",
            "Canalave Pokémon Center 1F",
            "Canalave Pokémon Center 2F",
            "Canalave Pokémon Center B1F",
            "Canalave Library 1F",
            "Canalave Library 2F",
            "Canalave Library 3F",
            "Canalave Private House 1 ()",
            "Canalave Private House 2 ()",
            "Canalave Private House 3 (Darkrai house?)",
            "Canalave Private House 4 ()",
            "Canalave Private House 5 ()",
            "Oreburgh City",
            "Oreburgh Poké Mart",
            "Oreburgh Oreburgh Gym (Rock)",
            "Oreburgh Pokémon Center 1F",
            "Oreburgh Pokémon Center 2F",
            "Oreburgh Pokémon Center B1F",
            "Oreburgh Building 1 1F (most NW)",
            "Oreburgh Building 1 2F (most NW)",
            "Oreburgh Building 2 1F (west of Mart)",
            "Oreburgh Building 2 2F (west of Mart)",
            "Oreburgh Private House 1 (west of Center)",
            "Oreburgh Mining Museum 1F",
            "Oreburgh Private House 2 (west of Gym)",
            "Oreburgh Building 3 1F (SE of Center)",
            "Oreburgh Building 3 2F (SE of Center)",
            "Oreburgh Private House 3 (near Mine)",
            "Eterna City",
            "Eterna Poké Mart",
            "Eterna Gym 1 (Grass) (Lobby)",
            "Eterna Gym 2 (Grass) (Main)",
            "Eterna Pokémon Center 1F",
            "Eterna Pokémon Center 2F",
            "Eterna Pokémon Center B1F",
            "Eterna Rad Rickshaw's Cycle Shop",
            "Team Galactic Eterna Building 1F",
            "Team Galactic Eterna Building 2F",
            "Team Galactic Eterna Building 3F",
            "Team Galactic Eterna Building 4F",
            "Eterna Condominums 1F (Name Rater) (Checked ZoneID)",
            "Eterna Condominums 2F",
            "Eterna Condominums 3F",
            "Eterna Cycling Road Gate",
            "Eterna Private House 1 (Herb Shop)",
            "Eterna Private House 2 (west of Gym)",
            "Eterna Private House 3 (south of Statue)",
            "Eterna Underground Man's House",
            "Hearthome City",
            "HeartHome Poké Mart",
            "HeartHome Gym (Ghost) (Lobby)",
            "HeartHome Gym (Ghost) (not there yet)",
            "HeartHome Gym (Ghost) (check zone id vs.)",
            "HeartHome Gym (Ghost) (trainers iirc?)",
            "HeartHome Gym (Ghost) ()",
            "HeartHome Gym (Ghost) ()",
            "HeartHome Gym (Ghost) ()",
            "HeartHome Gym (Ghost) ()",
            "HeartHome Gym (Ghost) ()",
            "HeartHome Gym (Ghost) ()",
            "HeartHome Gym (Ghost) ()",
            "HeartHome Gym (Ghost) ()",
            "HeartHome Gym (Ghost) ()",
            "HeartHome Pokémon Center 1F",
            "HeartHome Pokémon Center 2F",
            "HeartHome Pokémon Center B1F",
            "HeartHome Building 1 1F (east of Fanclub)",
            "HeartHome Building 1 2F (east of Fanclub)",
            "HeartHome Building 1 Elevator (east of Fanclub)",
            "HeartHome Pokémon Fan Club",
            "HeartHome Amity Square West Gate",
            "HeartHome Amity Square East Gate",
            "HeartHome Route 208 Gate",
            "HeartHome Route 209 Gate",
            "HeartHome Route 212 Gate",
            "HeartHome Building 2 1F (west of Gym)",
            "HeartHome Building 2 2F (west of Gym)",
            "HeartHome Building 2 Elevator (west of Gym)",
            "HeartHome Bebe's House (east of Center)",
            "HeartHome Poffin House (west of Mart)",
            "HeartHome Contest Hall (Main Lobby)",
            "HeartHome Contest Hall? (inaccessible?)",
            "HeartHome Contest Hall (Stage room)",
            "HeartHome Church",
            "Pastoria City",
            "Pastoria Poké Mart",
            "Pastoria Gym (Water)",
            "Pastoria Pokémon Center 1F",
            "Pastoria Pokémon Center 2F",
            "Pastoria Pokémon Center B1F",
            "Pastoria Great Marsh Gate 1F",
            "Pastoria Great Marsh Gate 2F",
            "Pastoria Private House 1 (west of Mart) (berry lady)",
            "Pastoria Private House 2 (north of Mart)",
            "Pastoria Private House 3 (Move Relearner)",
            "Pastoria Private House 4 (east of Gym)",
            "Pastoria Private House 5 (east of Marsh Gate) (ribbon guy)",
            "Veilstone City",
            "Veilstone Gym (Fighting)",
            "Veilstone Pokémon Center 1F",
            "Veilstone Pokémon Center 2F",
            "Veilstone Pokémon Center B1F",
            "Veilstone Style Shop (replaces Game Corner)",
            "Veilstone Department Store 1F",
            "Veilstone Department Store 2F",
            "Veilstone Department Store 3F",
            "Veilstone Department Store 4F",
            "Veilstone Department Store 5F",
            "Veilstone Department Store Elevator",
            "Veilstone Warehouse",
            "Veilstone Style Shop Storage (replaces Prize House)",
            "Veilstone Private House 1 (west of Style Shop)",
            "Veilstone Private House 2 (east of Dept. Store)",
            "Veilstone Private House 3 (north of Center)",
            "Veilstone Private House 4 (west of House 1))",
            "Veilstone Route 215 Gate",
            "Sunyshore Sunyshore City",
            "Sunyshore Poké Mart",
            "Sunyshore Gym (Electric) ()",
            "Sunyshore Gym (Electric) ()",
            "Sunyshore Gym (Electric) ()",
            "Sunyshore Pokémon Center 1F",
            "Sunyshore Pokémon Center 2F",
            "Sunyshore Pokémon Center B1F",
            "Sunyshore Market",
            "Sunyshore Private House 1 ()",
            "Sunyshore Private House 2 ()",
            "Sunyshore Private House 3 ()",
            "Sunyshore Private House 4 ()",
            "Sunyshore Private House 5 ()",
            "Sunyshore Private House 6 ()",
            "Sunyshore Vista Lighthouse Observation Deck",
            "Sunyshore Vista Lighthouse Elevator",
            "Snowpoint City",
            "Snowpoint Poké Mart",
            "Snowpoint Gym (Ice)",
            "Snowpoint Pokémon Center 1F",
            "Snowpoint Pokémon Center 2F",
            "Snowpoint Pokémon Center B1F",
            "Snowpoint Private House 1 ()",
            "Snowpoint Private House 2 ()",
            "Pokémon League",
            "Pokemon League Pokémon Center 1F",
            "Pokemon League Pokémon Center 2F",
            "Pokemon League Pokémon Center B1F",
            "Pokemon League",
            "Pokemon League",
            "Pokemon League",
            "Pokemon League",
            "Pokemon League",
            "Pokemon League",
            "Pokemon League",
            "Pokemon League",
            "Pokemon League",
            "Pokemon League",
            "Pokemon League",
            "Pokemon League",
            "Pokemon League",
            "Pokemon League",
            "Pokemon League",
            "Fight Area",
            "Fight Area: Poké Mart",
            "Fight Area: Pokémon Center 1F",
            "Fight Area: Pokémon Center 2F",
            "Fight Area: Pokémon Center B1F",
            "191",
            "Fight Area: Route 225 Gate",
            "Fight Area: Private House 1 ()",
            "Fight Area: Private House 2 ()",
            "Oreburgh Mine 1F",
            "Oreburgh Mine B1F",
            "Valley Windworks (Outside)",
            "Valley Windworks (Inside)",
            "Eterna Forest Exterior (Cut Tree Path)",
            "Eterna Forest",
            "Fuego Ironworks (Outside?)",
            "Fuego Ironworks (Inside?)",
            "Mt. Coronet ~ Route 207 Entrance",
            "Mt. Coronet ~ 2F",
            "Mt. Coronet ~ 3F",
            "Mt. Coronet ~ Snow Area",
            "Mt. Coronet ~ Summit",
            "Mt. Coronet ~ 4F",
            "Mt. Coronet ~ 5F",
            "Mt. Coronet ~ 6F",
            "Mt. Coronet ~ 7F",
            "Mt. Coronet ~ Summit",
            "Mt. Coronet ~ B1F",
            "Mt. Coronet ~ Route 211 Entrance",
            "Mt. Coronet ~ Route 216 Entrance",
            "216",
            "217",
            "218",
            "Great Marsh Area 1",
            "Great Marsh Area 2",
            "Great Marsh Area 3",
            "Great Marsh Area 4",
            "Great Marsh Area 5",
            "Great Marsh Area 6",
            "Solaceon Ruins",
            "Solaceon Ruins",
            "Solaceon Ruins",
            "Solaceon Ruins",
            "Solaceon Ruins",
            "Solaceon Ruins",
            "Solaceon Ruins",
            "Solaceon Ruins",
            "Solaceon Ruins",
            "Solaceon Ruins",
            "Solaceon Ruins",
            "Solaceon Ruins",
            "Solaceon Ruins",
            "Solaceon Ruins",
            "Solaceon Ruins",
            "Solaceon Ruins",
            "Solaceon Ruins",
            "Solaceon Ruins",
            "Solaceon Ruins",
            "Victory Road ~ 1F",
            "Victory Road ~ 2F",
            "Victory Road ~ B1F",
            "247",
            "248",
            "249",
            "250",
            "Amity Square (Hearthome)",
            "Ravaged Path",
            "Floral Path (Floaroma)",
            "Floral Path: Private House",
            "Oreburgh Tunnel 1F",
            "Oreburgh Tunnel B1F",
            "257",
            "258",
            "Stark Mountain (Outside)",
            "Stark Mountain (Entrance)",
            "Stark Mountain (Interior)",
            "262",
            "Sendoff Spring",
            "Turnback Cave",
            "Turnback Cave",
            "Turnback Cave",
            "Turnback Cave",
            "Turnback Cave",
            "Turnback Cave",
            "Turnback Cave",
            "Turnback Cave",
            "Turnback Cave",
            "Turnback Cave",
            "Turnback Cave",
            "Turnback Cave",
            "Turnback Cave",
            "Turnback Cave",
            "Turnback Cave",
            "Turnback Cave",
            "Turnback Cave",
            "Turnback Cave",
            "Turnback Cave",
            "Turnback Cave",
            "Turnback Cave",
            "Flower Paradise",
            "Snowpoint Temple",
            "Snowpoint Temple",
            "Snowpoint Temple",
            "Snowpoint Temple",
            "Snowpoint Temple",
            "Snowpoint Temple",
            "Wayward Cave",
            "Wayward Cave",
            "Maniac Tunnel",
            "Maniac Tunnel",
            "Maniac Tunnel",
            "Trophy Garden",
            "Iron Island (Outside)",
            "299",
            "300",
            "301",
            "302",
            "303",
            "304",
            "305",
            "Old Chateau",
            "Old Chateau",
            "Old Chateau",
            "Old Chateau",
            "Old Chateau",
            "Old Chateau",
            "Old Chateau",
            "Old Chateau",
            "Old Chateau",
            "Team Galactic HQ 1F",
            "Team Galactic HQ 2F",
            "Team Galactic HQ 3F",
            "Team Galactic HQ 4F",
            "319",
            "320",
            "321",
            "322",
            "Lake Verity (Before)",
            "Lake Verity (After)",
            "325",
            "326",
            "Lake Valor (After)",
            "328",
            "329",
            "Lake Acuity (After)",
            "331",
            "332",
            "333",
            "334",
            "335",
            "336",
            "337",
            "338",
            "339",
            "340",
            "341",
            "342",
            "343",
            "344",
            "345",
            "346",
            "Valor Lakefront",
            "348",
            "349",
            "350",
            "Acuity Lakefront",
            "352",
            "353",
            "Route 201",
            "Route 202",
            "Route 203",
            "Route 204 ~ South",
            "Route 204 ~ North",
            "Route 205 ~ South",
            "Route 205: Rest House",
            "Route 205 ~ North",
            "Route 206",
            "363",
            "Route 207",
            "Route 208",
            "366",
            "Route 209",
            "Lost Tower 1F",
            "Lost Tower 2F",
            "Lost Tower 3F",
            "Lost Tower 4F",
            "Lost Tower 5F",
            "Route 210 ~ South",
            "374",
            "Route 210 ~ North",
            "376",
            "Route 211 ~ West",
            "Route 211 ~ East",
            "Route 212 ~ North",
            "380",
            "381",
            "382",
            "Route 212 ~ South",
            "384",
            "Route 213",
            "386",
            "387",
            "388",
            "389",
            "390",
            "391",
            "Route 214",
            "393",
            "Route 215",
            "Route 216",
            "396",
            "Route 217",
            "398",
            "399",
            "Route 218",
            "Route 218: Jubilife Gate",
            "402",
            "Route 219",
            "Route 221",
            "405",
            "406",
            "Route 222",
            "408",
            "409",
            "410",
            "Route 224",
            "Route 225",
            "413",
            "Route 227",
            "415",
            "Route 228",
            "417",
            "418",
            "419",
            "Route 229",
            "421",
            "Twinleaf Town",
            "Twinleaf Rival's House 1F",
            "Twinleaf Rival's House 2F",
            "Twinleaf Player's House 1F",
            "Twinleaf Player's House 2F",
            "Twinleaf Private House 1 (north of Player house)",
            "Twinleaf Private House 2 (west of Player house)",
            "Sandgem Town",
            "Sandgem Poké Mart",
            "Sandgem Pokémon Center 1F",
            "Sandgem Pokémon Center 2F",
            "Sandgem Pokémon Center B1F",
            "Sandgem Pokémon Research Lab",
            "Sandgem Dawn/Lucas' House 1F",
            "Sandgem Dawn/Lucas' House 2F",
            "Sandgem Private House 1 (SW House)",
            "Floaroma Town",
            "Floaroma Poké Mart",
            "Floaroma Pokémon Center 1F",
            "Floaroma Pokémon Center 2F",
            "Floaroma Pokémon Center B1F",
            "Floaroma Flower Shop",
            "Floaroma Private House 1 (east of Center)",
            "Floaroma Private House 1 (NW of Center)",
            "Solaceon Town",
            "Solaceon Poké Mart",
            "Solaceon Pokémon Center 1F",
            "Solaceon Pokémon Center 2F",
            "Solaceon Pokémon Center B1F",
            "Solaceon Pokémon Nursery",
            "Solaceon Private House 1 ()",
            "Solaceon Private House 2 ()",
            "Solaceon Private House 3 ()",
            "Solaceon Private House 4 ()",
            "Celestic Town",
            "Celestic Pokémon Center 1F",
            "Celestic Pokémon Center 2F",
            "Celestic Pokémon Center B1F",
            "Celestic",
            "Celestic Private House 1 ()",
            "Celestic Private House 2 ()",
            "Celestic Private House 3 ()",
            "464",
            "Survival Area",
            "Survival Area: Poké Mart",
            "Survival Area: Pokémon Center 1F",
            "Survival Area: Pokémon Center 2F",
            "Survival Area: Pokémon Center B1F",
            "Survival Area: Private House 1 ()",
            "Survival Area: Private House 2 ()",
            "Survival Area: Private House 3 ()",
            "Resort Area",
            "Resort Area: Poké Mart",
            "Resort Area: Pokémon Center 1F",
            "Resort Area: Pokémon Center 2F",
            "Resort Area: Pokémon Center B1F",
            "Resort Area: Ribbon Syndicate 1F",
            "Resort Area: Ribbon Syndicate 2F",
            "Resort Area: Ribbon Syndicate Elevator",
            "Resort Area: Private House 1 ()",
            "Resort Area: Private House 2 ()",
            "483",
            "484",
            "Route 220",
            "Route 223",
            "Route 226",
            "Route 226: Private house",
            "Route 230",
            "490",
            "491",
            "492",
            "493",
            "494",
            "Ramanas Park",
            "Ramanas Park",
            "Ramanas Park",
            "Ramanas Park",
            "Ramanas Park",
            "Groudon's Ramanas Room",
            "Kyogre's Ramanas Room",
            "Rayquaza's Ramanas Room",
            "Ramanas Park",
            "Ramanas Park",
            "Ramanas Park",
            "Ramanas Park",
            "Ramanas Park",
            "508",
            "509",
            "510",
            "511",
            "512",
            "513",
            "514",
            "515",
            "516",
            "517",
            "518",
            "519",
            "520",
            "521",
            "522",
            "523",
            "524",
            "525",
            "526",
            "527",
            "528",
            "529",
            "530",
            "531",
            "532",
            "533",
            "534",
            "535",
            "536",
            "537",
            "538",
            "539",
            "540",
            "541",
            "542",
            "543",
            "544",
            "545",
            "546",
            "547",
            "548",
            "549",
            "550",
            "551",
            "552",
            "553",
            "554",
            "555",
            "556",
            "557",
            "558",
            "559",
            "560",
            "561",
            "562",
            "563",
            "564",
            "565",
            "566",
            "567",
            "568",
            "569",
            "570",
            "571",
            "572",
            "573",
            "574",
            "575",
            "576",
            "577",
            "578",
            "579",
            "580",
            "581",
            "582",
            "583",
            "584",
            "585",
            "586",
            "587",
            "588",
            "589",
            "590",
            "591",
            "592",
            "593",
            "594",
            "595",
            "596",
            "597",
            "598",
            "599",
            "600",
            "601",
            "602",
            "603",
            "604",
            "605",
            "606",
            "607",
            "608",
            "609",
            "610",
            "611",
            "612",
            "613",
            "614",
            "615",
            "616",
            "617",
            "618",
            "619",
            "620",
            "621",
            "622",
            "623",
            "624",
            "625",
            "Jubilife TV (?room behind guy in Clip Room)",
            "627",
            "628",
            "629",
            "630",
            "631",
            "632",
            "633",
            "634",
            "635",
            "636",
            "637",
            "638",
            "639",
            "640",
            "641",
            "642",
            "643",
            "644",
            "645",
            "646",
            "647",
            "648",
            "649",
            "650",
            "651",
            "652",
            "653",
            "654",
            "655",
            "656",
            "657",
            "UNKNOWN"
        };

        public enum PathEnum
        {
            EvScript,
            DprMasterdatas,
            Gamesettings,
            CommonMsbt,
            English,
            French,
            German,
            Italian,
            Jpn,
            JpnKanji,
            Korean,
            SimpChinese,
            Spanish,
            TradChinese,
            PersonalMasterdatas,
            Ugdata,
            BattleMasterdatas,
            UIMasterdatas
        }

        public enum LanguageNames
        {
            Jpn,
            Jpn_Kanji,
            English,
            French,
            Italian,
            German,
            Spanish,
            Korean,
            Simp_Chinese,
            Trad_Chinese
        }

        public enum AreaName
        {
            C01,
            C01FS0101,
            C01PC0101,
            C01PC0102,
            C01PC0103,
            C01R0101,
            C01R0102,
            C01R0103,
            C01R0201,
            C01R0202,
            C01R0203,
            C01R0204,
            C01R0205,
            C01R0206,
            C01R0207,
            C01R0208,
            C01R0301,
            C01R0302,
            C01R0501,
            C01R0502,
            C01R0601,
            C01R0701,
            C01R0801,
            C01R0802,
            C02,
            C02FS0101,
            C02GYM0101,
            C02PC0101,
            C02PC0102,
            C02PC0103,
            C02R0101,
            C02R0102,
            C02R0103,
            C02R0201,
            C02R0301,
            C02R0401,
            C02R0501,
            C02R0601,
            C03,
            C03FS0101,
            C03GYM0101,
            C03PC0101,
            C03PC0102,
            C03PC0103,
            C03R0101,
            C03R0102,
            C03R0201,
            C03R0202,
            C03R0301,
            C03R0401,
            C03R0501,
            C03R0601,
            C03R0602,
            C03R0701,
            C04,
            C04FS0101,
            C04GYM0101,
            C04GYM0102,
            C04PC0101,
            C04PC0102,
            C04PC0103,
            C04R0101,
            C04R0201,
            C04R0202,
            C04R0203,
            C04R0204,
            C04R0301,
            C04R0302,
            C04R0303,
            C04R0401,
            C04R0501,
            C04R0601,
            C04R0701,
            C04R0801,
            C05,
            C05FS0101,
            C05GYM0101,
            C05GYM0102,
            C05GYM0103,
            C05GYM0104,
            C05GYM0105,
            C05GYM0106,
            C05GYM0107,
            C05GYM0108,
            C05GYM0109,
            C05GYM0110,
            C05GYM0111,
            C05GYM0112,
            C05GYM0113,
            C05PC0101,
            C05PC0102,
            C05PC0103,
            C05R0101,
            C05R0102,
            C05R0103,
            C05R0201,
            C05R0301,
            C05R0401,
            C05R0501,
            C05R0601,
            C05R0701,
            C05R0801,
            C05R0802,
            C05R0803,
            C05R0901,
            C05R1001,
            C05R1101,
            C05R1102,
            C05R1103,
            C05R1201,
            C06,
            C06FS0101,
            C06GYM0101,
            C06PC0101,
            C06PC0102,
            C06PC0103,
            C06R0101,
            C06R0102,
            C06R0201,
            C06R0301,
            C06R0401,
            C06R0501,
            C06R0601,
            C07,
            C07GYM0101,
            C07PC0101,
            C07PC0102,
            C07PC0103,
            C07R0101,
            C07R0201,
            C07R0202,
            C07R0203,
            C07R0204,
            C07R0205,
            C07R0206,
            C07R0301,
            C07R0401,
            C07R0501,
            C07R0601,
            C07R0701,
            C07R0801,
            C07R0901,
            C08,
            C08FS0101,
            C08GYM0101,
            C08GYM0102,
            C08GYM0103,
            C08PC0101,
            C08PC0102,
            C08PC0103,
            C08R0101,
            C08R0201,
            C08R0301,
            C08R0401,
            C08R0501,
            C08R0601,
            C08R0701,
            C08R0801,
            C08R0802,
            C09,
            C09FS0101,
            C09GYM0101,
            C09PC0101,
            C09PC0102,
            C09PC0103,
            C09R0101,
            C09R0201,
            C10,
            C10PC0101,
            C10PC0102,
            C10PC0103,
            C10R0101,
            C10R0102,
            C10R0103,
            C10R0104,
            C10R0105,
            C10R0106,
            C10R0107,
            C10R0108,
            C10R0109,
            C10R0110,
            C10R0111,
            C10R0112,
            C10R0113,
            C10R0114,
            C10R0115,
            C11,
            C11FS0101,
            C11PC0101,
            C11PC0102,
            C11PC0103,
            C11R0101,
            C11R0201,
            C11R0301,
            C11R0401,
            D01R0101,
            D01R0102,
            D02,
            D02R0101,
            D03,
            D03R0101,
            D04,
            D04R0101,
            D05R0101,
            D05R0102,
            D05R0103,
            D05R0104,
            D05R0105,
            D05R0106,
            D05R0107,
            D05R0108,
            D05R0109,
            D05R0110,
            D05R0111,
            D05R0112,
            D05R0113,
            D05R0114,
            D05R0115,
            D05R0116,
            D06R0201,
            D06R0202,
            D06R0203,
            D06R0204,
            D06R0205,
            D06R0206,
            D07R0101,
            D07R0102,
            D07R0103,
            D07R0104,
            D07R0105,
            D07R0106,
            D07R0107,
            D07R0108,
            D07R0109,
            D07R0110,
            D07R0111,
            D07R0112,
            D07R0113,
            D07R0114,
            D07R0115,
            D07R0116,
            D07R0117,
            D07R0118,
            D07R0119,
            D09R0101,
            D09R0102,
            D09R0103,
            D09R0104,
            D09R0105,
            D09R0106,
            D10R0101,
            D11R0101,
            D12R0101,
            D13R0101,
            D13R0102,
            D14R0101,
            D14R0102,
            D15,
            D15R0101,
            D16,
            D16R0101,
            D16R0102,
            D16R0103,
            D17R0101,
            D17R0102,
            D17R0103,
            D17R0104,
            D17R0105,
            D17R0106,
            D17R0107,
            D17R0108,
            D17R0109,
            D17R0110,
            D17R0111,
            D17R0112,
            D17R0113,
            D17R0114,
            D17R0115,
            D17R0116,
            D17R0117,
            D17R0118,
            D17R0119,
            D17R0120,
            D17R0121,
            D17R0122,
            D18,
            D20R0101,
            D20R0102,
            D20R0103,
            D20R0104,
            D20R0105,
            D20R0106,
            D21R0101,
            D21R0102,
            D22R0101,
            D22R0102,
            D22R0103,
            D23R0101,
            D24,
            D24R0101,
            D24R0102,
            D24R0103,
            D24R0104,
            D24R0105,
            D24R0106,
            D24R0201,
            D25R0101,
            D25R0102,
            D25R0103,
            D25R0104,
            D25R0105,
            D25R0106,
            D25R0107,
            D25R0108,
            D25R0109,
            D26R0101,
            D26R0102,
            D26R0103,
            D26R0104,
            D26R0105,
            D26R0106,
            D26R0107,
            D26R0108,
            D27R0101,
            D27R0102,
            D27R0103,
            D28R0101,
            D28R0102,
            D28R0103,
            D29R0101,
            D29R0102,
            D29R0103,
            D30,
            D30R0101,
            D31,
            D31R0101,
            D31R0201,
            D31R0202,
            D31R0203,
            D31R0204,
            D31R0205,
            D31R0206,
            D31R0207,
            DIRECT2,
            DIRECT4,
            EVERYWHERE,
            L01,
            L02,
            L02R0101,
            L02R0201,
            L02R0301,
            L03,
            L04,
            NOTHING,
            R201,
            R202,
            R203,
            R204A,
            R204B,
            R205A,
            R205AR0101,
            R205B,
            R206,
            R206R0101,
            R207,
            R208,
            R208R0101,
            R209,
            R209R0101,
            R209R0102,
            R209R0103,
            R209R0104,
            R209R0105,
            R210A,
            R210AR0101,
            R210B,
            R210BR0101,
            R211A,
            R211B,
            R212A,
            R212AR0101,
            R212AR0102,
            R212AR0103,
            R212B,
            R212BR0101,
            R213,
            R213R0101,
            R213R0201,
            R213R0301,
            R213R0401,
            R213R0501,
            R213R0601,
            R214,
            R214R0101,
            R215,
            R216,
            R216R0101,
            R217,
            R217R0101,
            R217R0201,
            R218,
            R218R0101,
            R218R0201,
            R219,
            R221,
            R221R0101,
            R221R0201,
            R222,
            R222R0101,
            R222R0201,
            R222R0301,
            R224,
            R225,
            R225R0101,
            R227,
            R227R0101,
            R228,
            R228R0101,
            R228R0201,
            R228R0301,
            R229,
            RECORD,
            T01,
            T01R0101,
            T01R0102,
            T01R0201,
            T01R0202,
            T01R0301,
            T01R0401,
            T02,
            T02FS0101,
            T02PC0101,
            T02PC0102,
            T02PC0103,
            T02R0101,
            T02R0201,
            T02R0202,
            T02R0301,
            T03,
            T03FS0101,
            T03PC0101,
            T03PC0102,
            T03PC0103,
            T03R0101,
            T03R0201,
            T03R0301,
            T04,
            T04FS0101,
            T04PC0101,
            T04PC0102,
            T04PC0103,
            T04R0101,
            T04R0201,
            T04R0301,
            T04R0401,
            T04R0501,
            T05,
            T05PC0101,
            T05PC0102,
            T05PC0103,
            T05R0101,
            T05R0201,
            T05R0301,
            T05R0401,
            T05R0501,
            T06,
            T06FS0101,
            T06PC0101,
            T06PC0102,
            T06PC0103,
            T06R0101,
            T06R0201,
            T06R0301,
            T07,
            T07FS0101,
            T07PC0101,
            T07PC0102,
            T07PC0103,
            T07R0101,
            T07R0102,
            T07R0103,
            T07R0201,
            T07R0301,
            UG,
            UNION,
            W220,
            W223,
            W226,
            W226R0101,
            W230,
            W231,
            A01,
            A02,
            A03,
            A04,
            A05,
            A06,
            A07,
            A08,
            A09,
            A10,
            A11,
            A12,
            A13,
            A14,
            A15,
            Safari,
            UNION01,
            UNION02,
            UNION03,
            C04R0205,
            D10R0201,
            D10R0202,
            D10R0301,
            D10R0302,
            D10R0303,
            D10R0401,
            D10R0402,
            D10R0403,
            D10R0501,
            D10R0502,
            D10R0601,
            D10R0701,
            D10R0801,
            UGA01,
            UGA02,
            UGA03,
            UGA04,
            UGA05,
            UGA06,
            UGA07,
            UGA08,
            UGA09,
            UGA10,
            UGB01,
            UGB02,
            UGB03,
            UGB04,
            UGB05,
            UGB06,
            UGB07,
            UGC01,
            UGD01,
            UGD02,
            UGD03,
            UGD04,
            UGD05,
            UGE01,
            UGE02,
            UGE03,
            UGE04,
            UGE05,
            UGF01,
            UGF02,
            UGF03,
            UGF04,
            UGF05,
            UGF06,
            UGF07,
            UGSPACE01,
            UGSPACE02,
            UGSPACE03,
            UGSPACE04,
            UGSPACE05,
            UGSPACE06,
            UGSPACE07,
            UGSPACE08,
            UGSPACE09,
            UGSPACE10,
            UGSPACE11,
            UGSPACE12,
            UGSPACE13,
            UGSPACE14,
            UGSPACE15,
            UGSPACE16,
            UGSPACE17,
            UGSPACE18,
            UGSPACE19,
            UGSPACE20,
            UGSPACE21,
            UGSPACE22,
            UGSPACE23,
            UGSPACE24,
            UGSPACE25,
            UGSPACE26,
            UGSPACE27,
            UGSPACE28,
            UGSPACE29,
            UGSPACE30,
            UGSPACE31,
            UGSPACE32,
            UGSPACE33,
            UGSPACE34,
            UGSPACE35,
            UGSPACE36,
            UGSPACE37,
            UGSPACE38,
            UGSPACE39,
            UGSPACE40,
            UGSPACE41,
            UGSPACE42,
            UGSPACE43,
            UGSPACE44,
            UGSPACE45,
            UGSPACE46,
            UGSPACE47,
            UGSPACE48,
            UGSPACE49,
            UGSPACE50,
            UGSPACE51,
            UGSPACE52,
            UGSPACE53,
            UGSPACE54,
            UGSPACE55,
            UGSPACE56,
            UGSPACE57,
            UGSPACE58,
            UGSPACE59,
            UGSPACE60,
            UGSPACE61,
            UGSPACE62,
            UGSPACE63,
            UGSPACE64,
            UGSPACE65,
            UGSPACE66,
            UGSPACE67,
            UGSPACE68,
            UGSPACEL01,
            UGSPACEL02,
            UGSPACEL03,
            UGSPACEL04,
            UGSPACEL05,
            UGSPACEL06,
            UGSPACEL07,
            D05R0117,
            D10R0901,
            UGSECRETBASE01,
            UGSECRETBASE02,
            UGSECRETBASE03,
            UGSECRETBASE04,
            D10R0902,
            SEA01,
            C01R0209,
            UGAASECRETBASE01,
            UGAASECRETBASE02,
            UGAASECRETBASE03,
            UGABSECRETBASE01,
            UGABSECRETBASE02,
            UGABSECRETBASE03,
            UGBASECRETBASE01,
            UGBASECRETBASE02,
            UGBASECRETBASE03,
            UGCASECRETBASE01,
            UGCASECRETBASE02,
            UGCASECRETBASE03,
            UGDASECRETBASE01,
            UGDASECRETBASE02,
            UGDASECRETBASE03,
            UGEASECRETBASE01,
            UGEASECRETBASE02,
            UGEASECRETBASE03,
            UGFASECRETBASE01,
            UGFASECRETBASE02,
            UGFASECRETBASE03,
            D10R0202B,
            D10R0301B,
            D10R0302B,
            D10R0303B,
            D10R0401B,
            D10R0402B,
            D10R0403B,
            D10R0501B,
            D10R0502B,
            D10R0601B,
            UNKNOWN = -1
        }

        public enum AbsoluteBoundary
        {
            Level,
            BaseStat,
            CatchRate,
            EvYield,
            EvYieldTotal,
            InitialFriendship,
            ExpYield,
            LevelUpMoveCount,
            EggMoveCount,
            Power,
            Accuracy,
            Pp,
            TrainerPokemonCount,
            Iv,
            Ev,
            EvTotal,
            Price,
            None = -1
        }

        public static void Initialize()
        {
            randomizerPaths[PathEnum.BattleMasterdatas] = "romfs\\Data\\StreamingAssets\\AssetAssistant\\Battle\\battle_masterdatas";
            randomizerPaths[PathEnum.EvScript] = "romfs\\Data\\StreamingAssets\\AssetAssistant\\Dpr\\ev_script";
            randomizerPaths[PathEnum.DprMasterdatas] = "romfs\\Data\\StreamingAssets\\AssetAssistant\\Dpr\\masterdatas";
            randomizerPaths[PathEnum.Gamesettings] = "romfs\\Data\\StreamingAssets\\AssetAssistant\\Dpr\\scriptableobjects\\gamesettings";
            randomizerPaths[PathEnum.CommonMsbt] = "romfs\\Data\\StreamingAssets\\AssetAssistant\\Message\\common_msbt";
            randomizerPaths[PathEnum.English] = "romfs\\Data\\StreamingAssets\\AssetAssistant\\Message\\english";
            randomizerPaths[PathEnum.French] = "romfs\\Data\\StreamingAssets\\AssetAssistant\\Message\\french";
            randomizerPaths[PathEnum.German] = "romfs\\Data\\StreamingAssets\\AssetAssistant\\Message\\german";
            randomizerPaths[PathEnum.Italian] = "romfs\\Data\\StreamingAssets\\AssetAssistant\\Message\\italian";
            randomizerPaths[PathEnum.Jpn] = "romfs\\Data\\StreamingAssets\\AssetAssistant\\Message\\jpn";
            randomizerPaths[PathEnum.JpnKanji] = "romfs\\Data\\StreamingAssets\\AssetAssistant\\Message\\jpn_kanji";
            randomizerPaths[PathEnum.Korean] = "romfs\\Data\\StreamingAssets\\AssetAssistant\\Message\\korean";
            randomizerPaths[PathEnum.SimpChinese] = "romfs\\Data\\StreamingAssets\\AssetAssistant\\Message\\simp_chinese";
            randomizerPaths[PathEnum.Spanish] = "romfs\\Data\\StreamingAssets\\AssetAssistant\\Message\\spanish";
            randomizerPaths[PathEnum.TradChinese] = "romfs\\Data\\StreamingAssets\\AssetAssistant\\Message\\trad_chinese";
            randomizerPaths[PathEnum.PersonalMasterdatas] = "romfs\\Data\\StreamingAssets\\AssetAssistant\\Pml\\personal_masterdatas";
            randomizerPaths[PathEnum.UIMasterdatas] = "romfs\\Data\\StreamingAssets\\AssetAssistant\\UIs\\masterdatas\\uimasterdatas";
            randomizerPaths[PathEnum.Ugdata] = "romfs\\Data\\StreamingAssets\\AssetAssistant\\UnderGround\\data\\ugdata";
            DataColumn[] columns = { new DataColumn("Value", typeof(string)), new DataColumn("Minimum", typeof(int)), new DataColumn("Maximum", typeof(int)), new DataColumn("Increment", typeof(int)) };
            absoluteBoundaries.Columns.AddRange(columns);
            columns[0].ReadOnly = true;
            absoluteBoundaries.Rows.Add(new Object[] { "Level", 1, 100, 1 });
            absoluteBoundaries.Rows.Add(new Object[] { "Base Stat", 1, 255, 1 });
            absoluteBoundaries.Rows.Add(new Object[] { "Catch Rate", 1, 255, 1 });
            absoluteBoundaries.Rows.Add(new Object[] { "EV Yield", 0, 3, 1 });
            absoluteBoundaries.Rows.Add(new Object[] { "EV Yield Total", 1, 3, 1 });
            absoluteBoundaries.Rows.Add(new Object[] { "Initial Friendship", 0, 250, 10 });
            absoluteBoundaries.Rows.Add(new Object[] { "EXP Yield", 1, 65535, 1 });
            absoluteBoundaries.Rows.Add(new Object[] { "Level Up Move Count", 1, 255, 1 });
            absoluteBoundaries.Rows.Add(new Object[] { "Egg Move Count", 0, 255, 1 });
            absoluteBoundaries.Rows.Add(new Object[] { "Power", 5, 255, 5 });
            absoluteBoundaries.Rows.Add(new Object[] { "Accuracy", 5, 100, 5 });
            absoluteBoundaries.Rows.Add(new Object[] { "PP", 5, 40, 5 });
            absoluteBoundaries.Rows.Add(new Object[] { "Trainer Pokémon Count", 1, 6, 1 });
            absoluteBoundaries.Rows.Add(new Object[] { "IV", 0, 31, 1 });
            absoluteBoundaries.Rows.Add(new Object[] { "EV", 0, 255, 1 });
            absoluteBoundaries.Rows.Add(new Object[] { "EV Total", 0, 510, 1 });
            absoluteBoundaries.Rows.Add(new Object[] { "Price", 10, 999990, 10 });
        }
    }
}
